name: Run API tests
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select test environment'
        required: true
        type: environment
  pull_request:
    types: [opened, reopened, edited, synchronize]

jobs:
  runTests:
    name: Run API tests
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: ${{ github.event.inputs.environment || 'local' }}
      HOST_NAME: 'localhost'
      USER_NAME: 'postgres'
      DATABASE_NAME: 'postgres'
      PASSWORD: 'postgres'
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: ${{ env.USER_NAME }}
          POSTGRES_DB: ${{ env.DATABASE_NAME }}
          POSTGRES_PASSWORD: ${{ env.PASSWORD }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm install
      - name: Run application
        if: ${{ env.ENVIRONMENT == 'local' }}
        run: node index.js &
        env:
          APP_PID: $!
      - name: sleep 3 seconds
        if: ${{ env.ENVIRONMENT == 'local' }}
        run: sleep 3
      - name: Run API tests
        run: npm test
      - name: Stop application
        if: ${{ env.ENVIRONMENT == 'local' }}
        run: kill ${{ env.APP_PID }}

